services:
  dbjornada:
    image: postgres:17.5
    container_name: dbjornada
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: jornadadb
    volumes:
      - dbjornada_data:/var/lib/postgresql/data

volumes:
  dbjornada_data:
